config/routes.rb
Demo::Application.routes.draw do
  devise_for :users, skip: :registrations
  resources :people

  get '/events/:id/:edit' => "events#edit"
  get '/events/show_date' => "events#show_date", :as => "show_date"
  resources :events do
   collection do
      get :search
    end
  end
  resources :calendars

    root :to => "welcome#index"

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index", :as => :welcome
  get "welcome/events" => "events#index"
  
  get "welcome/companies" => "welcome#company", as: :company
  post "welcome/companies" => "welcome#create_company"
  get "welcome/company/:id" => "welcome#edit_company", as: :edit_company
  patch "welcome/company/:id" => "welcome#update_company"
  delete "welcome/company/:id" => "welcome#destroy_company"

  get "welcome/categories" => "welcome#category", as: :category
  post "welcome/categories" => "welcome#create_category"
  get "welcome/category/:id" => "welcome#edit_category", as: :edit_category
  patch "welcome/category/:id" => "welcome#update_category"
  delete "welcome/category/:id" => "welcome#destroy_category"

  get 'statistics' => 'statistics#show'

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!, :only => [ :index]
	before_action :set_company, only: [:edit_company, :update_company, :destroy_company]
	before_action :set_category, only: [:edit_category, :update_category, :destroy_category]


	def say
	end
	def index
		if params[:year]
			@year = params[:year].to_i
		else
			@year = Time.zone.now.year
		end

		if params[:month]
			@month = params[:month].to_i
		else
			@month = Time.zone.now.month
		end
		if 	@month > 12 
			@year = @year + 1
			@month = 1
		end
		if 	@month < 1
			@year = @year - 1
			@month = 12
		end
	end

	def company
		@companies = Company.all
	    @company = Company.new
	end
	def create_company
		@company = Company.new(company_params)
		@company.save
		redirect_to company_path
	end
	def edit_company

	end
	def update_company
      respond_to do |format|
        if @company.update(company_params)
          format.html { redirect_to company_path, notice: 'Company was successfully updated.' }
          format.json { head :no_content }
        end
      end
  	end
  	def destroy_company
    @company.destroy
      respond_to do |format|
      	format.html { redirect_to company_url }
      	format.json { head :no_content }
      end
  	end


	def category
		@categories = Category.all
	    @category = Category.new
	end
	def create_category
		@category = Category.new(category_params)
		@category.save
		redirect_to category_path
	end
	def edit_category

	end
	def update_category
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to category_path, notice: 'Category was successfully updated.' }
          format.json { head :no_content }
        end
      end
  	end
  	def destroy_category
    @category.destroy
      respond_to do |format|
      	format.html { redirect_to category_url }
      	format.json { head :no_content }
      end
  	end


 private

 	def set_company
 		@company = Company.find(params[:id])
 	end

 	def set_category
 		@category = Category.find(params[:id])
 	end

 	def category_params
      params.require(:category).permit(:name)
    end

    def company_params
    	params.require(:company).permit(:name)
    end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/category.html.erb
<h1>Listing 種類</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to "修改", edit_category_path(category) %></td>
        <td><%= link_to '刪除', edit_category_path(category), method: :delete, data: { confirm: '你確定嗎?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= form_for(@category, :url => category_path) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/company.html.erb
<h1>Listing 廟宇</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to "修改", edit_company_path(company) %></td>
        <td><%= link_to '刪除', edit_company_path(company), method: :delete, data: { confirm: '你確定嗎?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= form_for(@company, :url => company_path) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcome/edit_category.html.erb
<h1>修改種類名稱</h1>

<%= form_for(@category, :url => edit_category_path) do |f| %>
	<div class="field">
		<%= f.text_field :name %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

<%= link_to "back", category_path %>

app/views/welcome/edit_company.html.erb
<h1>修改廟宇名稱</h1>

<%= form_for(@company, :url => edit_company_path) do |f| %>
	<div class="field">
		<%= f.text_field :name %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

<%= link_to "back", company_path %>

app/views/welcome/index.html.erb
<h2>哈摟! 現在是 <%= Time.now %></h2>
<hr>
<h4><%= link_to 'Hello!' , welcome_say_hello_path %></h4>
<span>
<%= link_to 'Prev' , welcome_path(:year => @year, :month => @month-1), :class => "btn btn-info", :style => "margin-left:275px;"%>
<%= link_to 'Next' , welcome_path(:year => @year, :month => @month+1), :class => "btn btn-info", :style => "margin-left:50px;" %>
</span>
<%= calendar(:year => @year, :month => @month, :first_day_of_week => 1)%>

<script>
	$(document).ready(function(){
		$("td").click(function(){
			//alert($(this).attr("data-date"));
			$("td").removeClass("today");
			$(this).addClass("today");
			window.location = "<%= show_date_path() %>?date_time="+$(this).attr("data-date");
		});
	});
</script>

app/views/welcome/say.html.erb
<h1>Hello, 你好!</h1>
<p><%= link_to "Home", root_path %></p>