config/routes.rb
Demo::Application.routes.draw do
  devise_for :users, skip: :registrations
  resources :people

  get '/events/:id/:edit' => "events#edit"
  get '/events/show_date' => "events#show_date", :as => "show_date"
  resources :events do
   collection do
      get :search
    end
  end
  resources :calendars

    root :to => "welcome#index"

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index", :as => :welcome
  get "welcome/events" => "events#index"
  
  get "welcome/companies" => "welcome#company", as: :company
  post "welcome/companies" => "welcome#create_company"
  get "welcome/company/:id" => "welcome#edit_company", as: :edit_company
  patch "welcome/company/:id" => "welcome#update_company"
  delete "welcome/company/:id" => "welcome#destroy_company"

  get "welcome/categories" => "welcome#category", as: :category
  post "welcome/categories" => "welcome#create_category"
  get "welcome/category/:id" => "welcome#edit_category", as: :edit_category
  patch "welcome/category/:id" => "welcome#update_category"
  delete "welcome/category/:id" => "welcome#destroy_category"

  get 'statistics' => 'statistics#show'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Demo" %></title>
    <br><br><br>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Demo</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Calendar", welcome_path  %></li>
                  <% if user_signed_in? %>
              <li><%= link_to "建立廟宇", company_path %></li>
              <li><%= link_to "建立種類", category_path %></li>
              <li><%= link_to("登出", destroy_user_session_path ) %></li>
                  <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "所有訂單", welcome_events_path  %></li>
                <li><%= link_to "報表", statistics_path  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <hr>
        <p>Copyright &copy; booda406 2013 Fontech</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>